### ISSUE TITLE
Main Task

### ISSUE THREAD

**Issue by tigran-saatchyan** [tigran-saatchyan/UniMart_by_EvoQ#1]
Разработать API backend Сервис покупки товаров для авторизованных пользователей на Python. В качестве БД использовать PostgreSQL

- [x] tigran-saatchyan/UniMart_by_EvoQ#29 
- [x] tigran-saatchyan/UniMart_by_EvoQ#26 
- [x] tigran-saatchyan/UniMart_by_EvoQ#23 
- [x] tigran-saatchyan/UniMart_by_EvoQ#22 
- [x] tigran-saatchyan/UniMart_by_EvoQ#17 
- [x] tigran-saatchyan/UniMart_by_EvoQ#13 

- [x] tigran-saatchyan/UniMart_by_EvoQ#10
- [x] tigran-saatchyan/UniMart_by_EvoQ#9
- [x] tigran-saatchyan/UniMart_by_EvoQ#8
- [x] tigran-saatchyan/UniMart_by_EvoQ#7
