### ISSUE TITLE
Методы доступные авторизованным пользователям

### ISSUE THREAD

**Issue by tigran-saatchyan** [tigran-saatchyan/UniMart_by_EvoQ#13]
- [ ] tigran-saatchyan/EzyMart_by_EvoQ#19
- [x] tigran-saatchyan/UniMart_by_EvoQ#12
- [x] tigran-saatchyan/UniMart_by_EvoQ#11
