### ISSUE TITLE
Методы доступные неавторизованным пользователям

### ISSUE THREAD

**Issue by tigran-saatchyan** [tigran-saatchyan/UniMart_by_EvoQ#17]
- [ ] tigran-saatchyan/UniMart_by_EvoQ#16
- [ ] tigran-saatchyan/UniMart_by_EvoQ#15
- [ ] tigran-saatchyan/UniMart_by_EvoQ#14
