### ISSUE TITLE
Cart implementation

### ISSUE THREAD

**Issue by tigran-saatchyan** [tigran-saatchyan/UniMart_by_EvoQ#22]
- [x] tigran-saatchyan/UniMart_by_EvoQ#21
- [x] tigran-saatchyan/UniMart_by_EvoQ#20
- [x] tigran-saatchyan/UniMart_by_EvoQ#19
- [x] tigran-saatchyan/UniMart_by_EvoQ#18
