### ISSUE TITLE
user model and registration

### ISSUE THREAD

**Issue by tigran-saatchyan** [tigran-saatchyan/UniMart_by_EvoQ#29]
- [x] tigran-saatchyan/UniMart_by_EvoQ#28
- [x] tigran-saatchyan/UniMart_by_EvoQ#4

- [x] tigran-saatchyan/UniMart_by_EvoQ#27
